### PR TITLE
add flag -D useSetTimeout=true for use setTimeout instead of setImmediate

### PR DESCRIPTION
**Pull request by francescoagati**

### CODE REVIEW

**Comment by jdonaldson** [comment]
were you able to override the default event loop with setTimeout manually?  Was chrome able to jit it efficiently?

**Comment by francescoagati** [comment]
Explorer is alow with setimmediate if there are mamy events to process

**Comment by francescoagati** [comment]
Slow

**Comment by francescoagati** [comment]
ok with manually update nextLoop it works good. Thanks.

This is the code for manual nextLoop
```
    promhx.base.EventLoop.nextLoop = function(f) {
      untyped setTimeout(f,0);
    };
```

**Pull request closed without merging**
