### PR TITLE
fixed: when macro does not handle function calls properly

### PR DESCRIPTION
**Pull request by modjke**
for https://github.com/jdonaldson/promhx/issues/61

### CODE REVIEW

**Comment by jdonaldson** [comment]
Thanks for this, I'll take a look this week sometime.

**Comment by alebianco** [comment]
+1 for this
i spent a couple of hours today trying to figure out why my services where called twice

**Comment by jdonaldson** [comment]
got a bit delayed due to a wedding... but it's next in my queue.

**Comment by jdonaldson** [comment]
this is in, thanks again.

**Pull request closed without merging**
